import { normalizeCityKey, normalizeStateCode } from "@/lib/service-area/normalize";

/** Canonical NYC names plus neighborhoods used when ZIP is missing. */
const NYC_CITY_ALIAS_LIST = [
  "new york",
  "new york city",
  "new york, ny",
  "nyc",
  "ny c",
  "city of new york",
  "manhattan",
  "brooklyn",
  "queens",
  "bronx",
  "the bronx",
  "staten island",
  "statenisland",
  "bklyn",
  "bk",
  "astoria",
  "long island city",
  "lic",
  "flushing",
  "jamaica",
  "williamsburg",
  "harlem",
  "east harlem",
  "spanish harlem",
  "upper manhattan",
  "lower manhattan",
  "midtown",
  "midtown manhattan",
  "chelsea",
  "soho",
  "tribeca",
  "greenwich village",
  "east village",
  "west village",
  "upper east side",
  "upper west side",
  "financial district",
  "hells kitchen",
  "hell's kitchen",
  "washington heights",
  "inwood",
  "morningside heights",
  "chinatown",
  "noho",
  "nolita",
  "flatiron",
  "times square",
  "hudson yards",
  "kips bay",
  "murray hill",
  "gramercy",
  "battery park",
  "battery park city",
  "bushwick",
  "park slope",
  "dumbo",
  "brooklyn heights",
  "bedford stuyvesant",
  "bed stuy",
  "bed-stuy",
  "crown heights",
  "flatbush",
  "greenpoint",
  "fort greene",
  "cobble hill",
  "carroll gardens",
  "red hook",
  "sunset park",
  "bay ridge",
  "bensonhurst",
  "coney island",
  "brighton beach",
  "downtown brooklyn",
  "prospect heights",
  "clinton hill",
  "boerum hill",
  "ditmas park",
  "east new york",
  "brownsville",
  "sheepshead bay",
  "canarsie",
  "windsor terrace",
  "kensington",
  "forest hills",
  "jackson heights",
  "elmhurst",
  "corona",
  "woodside",
  "sunnyside",
  "ridgewood",
  "maspeth",
  "rego park",
  "kew gardens",
  "bayside",
  "whitestone",
  "college point",
  "far rockaway",
  "rockaway",
  "howard beach",
  "ozone park",
  "richmond hill",
  "woodhaven",
  "glendale",
  "middle village",
  "hunters point",
  "hunter's point",
  "dutch kills",
  "ravenswood",
  "east elmhurst",
  "fresh meadows",
  "hollis",
  "briarwood",
  "queens village",
  "springfield gardens",
  "laurelton",
  "rosedale",
  "st albans",
  "saint albans",
  "riverdale",
  "fordham",
  "mott haven",
  "hunts point",
  "soundview",
  "parkchester",
  "throgs neck",
  "throggs neck",
  "city island",
  "co-op city",
  "coop city",
  "pelham bay",
  "kingsbridge",
  "norwood",
  "bedford park",
  "university heights",
  "morrisania",
  "highbridge",
  "south bronx",
  "wakefield",
  "woodlawn",
  "castle hill",
  "st george",
  "saint george",
  "st. george",
  "tottenville",
  "great kills",
  "new dorp",
  "port richmond",
  "stapleton",
  "tompkinsville",
  "new springville",
  "eltingville",
  "oakwood",
  "south beach",
] as const;

export const NYC_CITY_ALIASES: ReadonlySet<string> = new Set(
  NYC_CITY_ALIAS_LIST.map((alias) => normalizeCityKey(alias))
);

export function isNycHoldPolicy(policy: { code?: string | null; states?: string[] | null }): boolean {
  if (String(policy.code ?? "").trim().toUpperCase() === "NYC") return true;
  const states = (policy.states ?? []).map((state) => normalizeStateCode(state));
  return states.length === 1 && states[0] === "NY";
}

export function isNewYorkCityPlace(
  city: string | null | undefined,
  options?: { state?: string | null }
): boolean {
  const state = normalizeStateCode(options?.state);
  if (state && state !== "NY") return false;
  const key = normalizeCityKey(city);
  return Boolean(key && NYC_CITY_ALIASES.has(key));
}
