-- Global brassHR platform FAQs for applicant portal help assistant

DELETE FROM public.faqs
WHERE tenant_id IS NULL
  AND category = 'brassHR Platform';

INSERT INTO public.faqs (tenant_id, category, question, answer)
VALUES
  (NULL, 'brassHR Platform', 'What is brassHR?', 'brassHR is a white-labeled, multi-tenant mini-HR SaaS platform designed to simplify HR operations for growing teams. It helps companies manage applicant onboarding, worker documentation, eSign workflows, timekeeping, PTO, and payroll-ready exports in one branded system.'),
  (NULL, 'brassHR Platform', 'Who is brassHR built for?', 'brassHR is built for staffing companies, healthcare staffing teams, small to mid-sized businesses, and growing organizations that need a simple but secure HR platform for onboarding, compliance, scheduling, and workforce management.'),
  (NULL, 'brassHR Platform', 'What problems does brassHR solve?', 'brassHR helps reduce manual HR work, scattered documents, separate signing tools, and inconsistent onboarding processes. It gives each tenant a secure, branded workspace where they can manage applicants, workers, documents, eSignatures, audit trails, timekeeping, PTO, and HR workflows.'),
  (NULL, 'brassHR Platform', 'What makes brassHR different from a generic HR tool?', 'brassHR is being built from the proven ZipStaff onboarding, ATS, scheduling, and timekeeping system. Instead of being a one-size-fits-all HR platform, it is focused on configurable workflows, tenant branding, embedded signing, staffing-style onboarding, and secure client-level isolation.'),
  (NULL, 'brassHR Platform', 'Is brassHR a SaaS product?', 'Yes. brassHR is being designed as a SaaS platform. The first version will be used internally, and the long-term goal is to offer it externally to clients as a white-labeled, multi-tenant HR platform.'),
  (NULL, 'brassHR Platform', 'What does white-labeled mean in brassHR?', 'White-labeled means each client or tenant can use brassHR under their own branding. This can include their company name, logo, colors, branded templates, and client-specific HR documents.'),
  (NULL, 'brassHR Platform', 'What does multi-tenant mean?', 'Multi-tenant means multiple client organizations can use the same brassHR platform while keeping their data fully separated. Each tenant has its own users, templates, documents, applicant records, worker records, audit logs, and configurations.'),
  (NULL, 'brassHR Platform', 'How does brassHR protect client data?', 'brassHR is designed with tenant isolation in mind. Each tenant''s templates, documents, agreements, audit logs, and worker data are separated so one client cannot access another client''s information.'),
  (NULL, 'brassHR Platform', 'Why is tenant isolation important?', 'Tenant isolation is critical because HR systems store sensitive documents, employment agreements, tax forms, background authorization forms, audit logs, and personal worker information. Without proper separation, a shared system could create security, privacy, and compliance risks.'),
  (NULL, 'brassHR Platform', 'What HR workflows does brassHR support?', 'brassHR supports applicant onboarding, worker onboarding, HR document collection, eSigning, document acknowledgments, scheduling, geofenced time clock, PTO tracking, and payroll-ready exports.'),
  (NULL, 'brassHR Platform', 'Can applicants sign documents inside brassHR?', 'Yes. Applicants and workers can complete eSign workflows directly inside the brassHR web and mobile apps. This can include background check authorizations, employment agreements, tax forms, handbook acknowledgments, and other onboarding documents.'),
  (NULL, 'brassHR Platform', 'Does brassHR support embedded signing?', 'Yes. brassHR is intended to support a smooth embedded signing experience using an iFrame or SDK-style flow, so applicants and workers can complete documents without leaving the platform.'),
  (NULL, 'brassHR Platform', 'Can HR admins manage their own templates?', 'Yes. Tenant HR admins should be able to configure and manage their own branded templates directly inside brassHR without needing a separate login to another tool.'),
  (NULL, 'brassHR Platform', 'What kinds of templates can tenants manage?', 'Tenants may manage templates such as employment agreements, background authorization forms, handbook acknowledgments, tax-related forms, onboarding packets, policy acknowledgments, and other HR documents.'),
  (NULL, 'brassHR Platform', 'Will each tenant have its own branded documents?', 'Yes. Each tenant can have its own branded document templates, allowing them to present forms, agreements, and onboarding packets under their own company identity.'),
  (NULL, 'brassHR Platform', 'Does brassHR support audit trails?', 'Yes. brassHR is designed to maintain strong audit trails for document signing, HR actions, onboarding progress, and compliance-related activities.'),
  (NULL, 'brassHR Platform', 'Why are audit trails important in brassHR?', 'Audit trails help prove who signed what, when they signed it, what document version was used, and what actions were taken during onboarding or HR processing. This is especially important for regulated industries such as healthcare staffing.'),
  (NULL, 'brassHR Platform', 'Does brassHR support healthcare staffing use cases?', 'Yes. brassHR is especially relevant for healthcare staffing workflows because those teams often require strict onboarding, background checks, document compliance, credential tracking, employment agreements, and reliable audit records.'),
  (NULL, 'brassHR Platform', 'Does brassHR include timekeeping?', 'Yes. brassHR includes timekeeping features such as geofenced time clock functionality, allowing workers to clock in and out based on approved job locations.'),
  (NULL, 'brassHR Platform', 'What is a geofenced time clock?', 'A geofenced time clock allows workers to clock in or out only when they are within an approved geographic area, such as a client site, office, or facility location.'),
  (NULL, 'brassHR Platform', 'Does brassHR support PTO?', 'Yes. brassHR is intended to support PTO tracking so workers and HR admins can manage time-off requests and balances more easily.'),
  (NULL, 'brassHR Platform', 'Can brassHR export payroll-ready data?', 'Yes. brassHR is designed to generate payroll-ready exports so approved timekeeping and HR data can be prepared for payroll processing.'),
  (NULL, 'brassHR Platform', 'Will brassHR replace all HR systems?', 'Not necessarily. brassHR is positioned as a mini-HR platform focused on simplifying core workflows such as onboarding, document signing, timekeeping, PTO, and payroll exports. It may integrate with or complement larger payroll, HRIS, or accounting systems.'),
  (NULL, 'brassHR Platform', 'What is included in MVP-1?', 'MVP-1 focuses on the core brassHR experience needed to validate the platform: applicant and worker onboarding, document/eSign workflows, tenant configuration, branded templates, secure tenant separation, and foundational HR operations.'),
  (NULL, 'brassHR Platform', 'Can brassHR be used on mobile?', 'Yes. brassHR is designed to support both web and mobile app experiences, especially for applicants and workers completing onboarding tasks, signing documents, and managing timekeeping.'),
  (NULL, 'brassHR Platform', 'Why is brassHR being built from ZipStaff?', 'ZipStaff already has proven workflows for onboarding, ATS, scheduling, and timekeeping. brassHR evolves those capabilities into a configurable SaaS platform that can be used by external clients under their own branding.'),
  (NULL, 'brassHR Platform', 'Will clients need separate logins for document signing tools?', 'The goal is no. brassHR is intended to provide embedded document and eSign workflows directly inside the platform, so tenant admins, applicants, and workers do not need to jump between separate systems.'),
  (NULL, 'brassHR Platform', 'What does "HR simplified for growing teams" mean?', 'It means brassHR helps growing companies handle essential HR tasks without needing a large HR department or multiple disconnected tools. The platform brings onboarding, documents, eSignatures, timekeeping, PTO, and payroll exports into one streamlined system.'),
  (NULL, 'brassHR Platform', 'Is brassHR secure enough for client-specific agreements and documents?', 'Security and data isolation are core design priorities. brassHR is being developed to avoid the risks of using a single shared account by giving each tenant separated templates, documents, audit logs, and configurations.'),
  (NULL, 'brassHR Platform', 'What is the long-term vision for brassHR?', 'The long-term vision is to turn brassHR into a configurable, white-labeled SaaS mini-HR platform that external clients can use to manage onboarding, HR documents, eSignatures, timekeeping, PTO, and payroll-ready workflows under their own brand.');
