-- Seed major US cities for all states (signup business info city dropdown).
-- Safe to re-run: uses ON CONFLICT DO NOTHING.

INSERT INTO public.signup_us_cities (state_code, city_name, sort_order) VALUES
  ('AL', 'Birmingham', 1),
  ('AL', 'Montgomery', 2),
  ('AL', 'Huntsville', 3),
  ('AL', 'Mobile', 4),
  ('AL', 'Tuscaloosa', 5),
  ('AL', 'Hoover', 6),
  ('AL', 'Auburn', 7),
  ('AL', 'Dothan', 8),
  ('AK', 'Anchorage', 1),
  ('AK', 'Fairbanks', 2),
  ('AK', 'Juneau', 3),
  ('AK', 'Sitka', 4),
  ('AK', 'Ketchikan', 5),
  ('AK', 'Wasilla', 6),
  ('AK', 'Kenai', 7),
  ('AK', 'Kodiak', 8),
  ('AZ', 'Phoenix', 1),
  ('AZ', 'Tucson', 2),
  ('AZ', 'Mesa', 3),
  ('AZ', 'Chandler', 4),
  ('AZ', 'Scottsdale', 5),
  ('AZ', 'Glendale', 6),
  ('AZ', 'Gilbert', 7),
  ('AZ', 'Tempe', 8),
  ('AZ', 'Peoria', 9),
  ('AZ', 'Surprise', 10),
  ('AR', 'Little Rock', 1),
  ('AR', 'Fort Smith', 2),
  ('AR', 'Fayetteville', 3),
  ('AR', 'Springdale', 4),
  ('AR', 'Jonesboro', 5),
  ('AR', 'Rogers', 6),
  ('AR', 'Conway', 7),
  ('AR', 'North Little Rock', 8),
  ('CA', 'Los Angeles', 1),
  ('CA', 'San Diego', 2),
  ('CA', 'San Jose', 3),
  ('CA', 'San Francisco', 4),
  ('CA', 'Fresno', 5),
  ('CA', 'Sacramento', 6),
  ('CA', 'Long Beach', 7),
  ('CA', 'Oakland', 8),
  ('CA', 'Bakersfield', 9),
  ('CA', 'Anaheim', 10),
  ('CA', 'Santa Ana', 11),
  ('CA', 'Riverside', 12),
  ('CA', 'Stockton', 13),
  ('CA', 'Irvine', 14),
  ('CA', 'Chula Vista', 15),
  ('CO', 'Denver', 1),
  ('CO', 'Colorado Springs', 2),
  ('CO', 'Aurora', 3),
  ('CO', 'Fort Collins', 4),
  ('CO', 'Lakewood', 5),
  ('CO', 'Thornton', 6),
  ('CO', 'Arvada', 7),
  ('CO', 'Westminster', 8),
  ('CO', 'Pueblo', 9),
  ('CO', 'Boulder', 10),
  ('CT', 'Bridgeport', 1),
  ('CT', 'New Haven', 2),
  ('CT', 'Stamford', 3),
  ('CT', 'Hartford', 4),
  ('CT', 'Waterbury', 5),
  ('CT', 'Norwalk', 6),
  ('CT', 'Danbury', 7),
  ('CT', 'New Britain', 8),
  ('DE', 'Wilmington', 1),
  ('DE', 'Dover', 2),
  ('DE', 'Newark', 3),
  ('DE', 'Middletown', 4),
  ('DE', 'Smyrna', 5),
  ('DE', 'Milford', 6),
  ('DE', 'Seaford', 7),
  ('DE', 'Georgetown', 8),
  ('FL', 'Jacksonville', 1),
  ('FL', 'Miami', 2),
  ('FL', 'Tampa', 3),
  ('FL', 'Orlando', 4),
  ('FL', 'St. Petersburg', 5),
  ('FL', 'Hialeah', 6),
  ('FL', 'Tallahassee', 7),
  ('FL', 'Fort Lauderdale', 8),
  ('FL', 'Port St. Lucie', 9),
  ('FL', 'Cape Coral', 10),
  ('FL', 'Pembroke Pines', 11),
  ('FL', 'Hollywood', 12),
  ('GA', 'Atlanta', 1),
  ('GA', 'Augusta', 2),
  ('GA', 'Columbus', 3),
  ('GA', 'Macon', 4),
  ('GA', 'Savannah', 5),
  ('GA', 'Athens', 6),
  ('GA', 'Sandy Springs', 7),
  ('GA', 'Roswell', 8),
  ('GA', 'Albany', 9),
  ('GA', 'Johns Creek', 10),
  ('HI', 'Honolulu', 1),
  ('HI', 'Pearl City', 2),
  ('HI', 'Hilo', 3),
  ('HI', 'Kailua', 4),
  ('HI', 'Waipahu', 5),
  ('HI', 'Kaneohe', 6),
  ('HI', 'Mililani', 7),
  ('HI', 'Kahului', 8),
  ('ID', 'Boise', 1),
  ('ID', 'Meridian', 2),
  ('ID', 'Nampa', 3),
  ('ID', 'Idaho Falls', 4),
  ('ID', 'Pocatello', 5),
  ('ID', 'Caldwell', 6),
  ('ID', 'Coeur d''Alene', 7),
  ('ID', 'Twin Falls', 8),
  ('IL', 'Chicago', 1),
  ('IL', 'Aurora', 2),
  ('IL', 'Naperville', 3),
  ('IL', 'Joliet', 4),
  ('IL', 'Rockford', 5),
  ('IL', 'Springfield', 6),
  ('IL', 'Elgin', 7),
  ('IL', 'Peoria', 8),
  ('IL', 'Champaign', 9),
  ('IL', 'Waukegan', 10),
  ('IN', 'Indianapolis', 1),
  ('IN', 'Fort Wayne', 2),
  ('IN', 'Evansville', 3),
  ('IN', 'South Bend', 4),
  ('IN', 'Carmel', 5),
  ('IN', 'Bloomington', 6),
  ('IN', 'Fishers', 7),
  ('IN', 'Hammond', 8),
  ('IN', 'Lafayette', 9),
  ('IN', 'Muncie', 10),
  ('IA', 'Des Moines', 1),
  ('IA', 'Cedar Rapids', 2),
  ('IA', 'Davenport', 3),
  ('IA', 'Sioux City', 4),
  ('IA', 'Iowa City', 5),
  ('IA', 'Waterloo', 6),
  ('IA', 'Ames', 7),
  ('IA', 'West Des Moines', 8),
  ('KS', 'Wichita', 1),
  ('KS', 'Overland Park', 2),
  ('KS', 'Kansas City', 3),
  ('KS', 'Olathe', 4),
  ('KS', 'Topeka', 5),
  ('KS', 'Lawrence', 6),
  ('KS', 'Shawnee', 7),
  ('KS', 'Manhattan', 8),
  ('KY', 'Louisville', 1),
  ('KY', 'Lexington', 2),
  ('KY', 'Bowling Green', 3),
  ('KY', 'Owensboro', 4),
  ('KY', 'Covington', 5),
  ('KY', 'Richmond', 6),
  ('KY', 'Georgetown', 7),
  ('KY', 'Florence', 8),
  ('LA', 'New Orleans', 1),
  ('LA', 'Baton Rouge', 2),
  ('LA', 'Shreveport', 3),
  ('LA', 'Lafayette', 4),
  ('LA', 'Lake Charles', 5),
  ('LA', 'Kenner', 6),
  ('LA', 'Bossier City', 7),
  ('LA', 'Monroe', 8),
  ('ME', 'Portland', 1),
  ('ME', 'Lewiston', 2),
  ('ME', 'Bangor', 3),
  ('ME', 'South Portland', 4),
  ('ME', 'Auburn', 5),
  ('ME', 'Biddeford', 6),
  ('ME', 'Sanford', 7),
  ('ME', 'Augusta', 8),
  ('MD', 'Baltimore', 1),
  ('MD', 'Frederick', 2),
  ('MD', 'Rockville', 3),
  ('MD', 'Gaithersburg', 4),
  ('MD', 'Bowie', 5),
  ('MD', 'Hagerstown', 6),
  ('MD', 'Annapolis', 7),
  ('MD', 'College Park', 8),
  ('MA', 'Boston', 1),
  ('MA', 'Worcester', 2),
  ('MA', 'Springfield', 3),
  ('MA', 'Cambridge', 4),
  ('MA', 'Lowell', 5),
  ('MA', 'Brockton', 6),
  ('MA', 'Quincy', 7),
  ('MA', 'Lynn', 8),
  ('MA', 'New Bedford', 9),
  ('MA', 'Fall River', 10),
  ('MI', 'Detroit', 1),
  ('MI', 'Grand Rapids', 2),
  ('MI', 'Warren', 3),
  ('MI', 'Sterling Heights', 4),
  ('MI', 'Ann Arbor', 5),
  ('MI', 'Lansing', 6),
  ('MI', 'Flint', 7),
  ('MI', 'Dearborn', 8),
  ('MI', 'Troy', 9),
  ('MI', 'Kalamazoo', 10),
  ('MN', 'Minneapolis', 1),
  ('MN', 'St. Paul', 2),
  ('MN', 'Rochester', 3),
  ('MN', 'Duluth', 4),
  ('MN', 'Bloomington', 5),
  ('MN', 'Brooklyn Park', 6),
  ('MN', 'Plymouth', 7),
  ('MN', 'St. Cloud', 8),
  ('MN', 'Eagan', 9),
  ('MN', 'Woodbury', 10),
  ('MS', 'Jackson', 1),
  ('MS', 'Gulfport', 2),
  ('MS', 'Southaven', 3),
  ('MS', 'Hattiesburg', 4),
  ('MS', 'Biloxi', 5),
  ('MS', 'Meridian', 6),
  ('MS', 'Tupelo', 7),
  ('MS', 'Olive Branch', 8),
  ('MO', 'Kansas City', 1),
  ('MO', 'St. Louis', 2),
  ('MO', 'Springfield', 3),
  ('MO', 'Columbia', 4),
  ('MO', 'Independence', 5),
  ('MO', 'Lee''s Summit', 6),
  ('MO', 'O''Fallon', 7),
  ('MO', 'St. Joseph', 8),
  ('MO', 'St. Charles', 9),
  ('MO', 'Blue Springs', 10),
  ('MT', 'Billings', 1),
  ('MT', 'Missoula', 2),
  ('MT', 'Great Falls', 3),
  ('MT', 'Bozeman', 4),
  ('MT', 'Butte', 5),
  ('MT', 'Helena', 6),
  ('MT', 'Kalispell', 7),
  ('MT', 'Havre', 8),
  ('NE', 'Omaha', 1),
  ('NE', 'Lincoln', 2),
  ('NE', 'Bellevue', 3),
  ('NE', 'Grand Island', 4),
  ('NE', 'Kearney', 5),
  ('NE', 'Fremont', 6),
  ('NE', 'Hastings', 7),
  ('NE', 'Norfolk', 8),
  ('NV', 'Las Vegas', 1),
  ('NV', 'Henderson', 2),
  ('NV', 'Reno', 3),
  ('NV', 'North Las Vegas', 4),
  ('NV', 'Sparks', 5),
  ('NV', 'Carson City', 6),
  ('NV', 'Elko', 7),
  ('NV', 'Mesquite', 8),
  ('NH', 'Manchester', 1),
  ('NH', 'Nashua', 2),
  ('NH', 'Concord', 3),
  ('NH', 'Derry', 4),
  ('NH', 'Dover', 5),
  ('NH', 'Rochester', 6),
  ('NH', 'Salem', 7),
  ('NH', 'Merrimack', 8),
  ('NJ', 'Newark', 1),
  ('NJ', 'Jersey City', 2),
  ('NJ', 'Paterson', 3),
  ('NJ', 'Elizabeth', 4),
  ('NJ', 'Edison', 5),
  ('NJ', 'Woodbridge', 6),
  ('NJ', 'Lakewood', 7),
  ('NJ', 'Toms River', 8),
  ('NJ', 'Hamilton', 9),
  ('NJ', 'Trenton', 10),
  ('NM', 'Albuquerque', 1),
  ('NM', 'Las Cruces', 2),
  ('NM', 'Rio Rancho', 3),
  ('NM', 'Santa Fe', 4),
  ('NM', 'Roswell', 5),
  ('NM', 'Farmington', 6),
  ('NM', 'Clovis', 7),
  ('NM', 'Hobbs', 8),
  ('NY', 'New York', 1),
  ('NY', 'Buffalo', 2),
  ('NY', 'Rochester', 3),
  ('NY', 'Yonkers', 4),
  ('NY', 'Syracuse', 5),
  ('NY', 'Albany', 6),
  ('NY', 'New Rochelle', 7),
  ('NY', 'Mount Vernon', 8),
  ('NY', 'Schenectady', 9),
  ('NY', 'Utica', 10),
  ('NC', 'Charlotte', 1),
  ('NC', 'Raleigh', 2),
  ('NC', 'Greensboro', 3),
  ('NC', 'Durham', 4),
  ('NC', 'Winston-Salem', 5),
  ('NC', 'Fayetteville', 6),
  ('NC', 'Cary', 7),
  ('NC', 'Wilmington', 8),
  ('NC', 'High Point', 9),
  ('NC', 'Concord', 10),
  ('ND', 'Fargo', 1),
  ('ND', 'Bismarck', 2),
  ('ND', 'Grand Forks', 3),
  ('ND', 'Minot', 4),
  ('ND', 'West Fargo', 5),
  ('ND', 'Williston', 6),
  ('ND', 'Dickinson', 7),
  ('ND', 'Mandan', 8),
  ('OH', 'Columbus', 1),
  ('OH', 'Cleveland', 2),
  ('OH', 'Cincinnati', 3),
  ('OH', 'Toledo', 4),
  ('OH', 'Akron', 5),
  ('OH', 'Dayton', 6),
  ('OH', 'Parma', 7),
  ('OH', 'Canton', 8),
  ('OH', 'Youngstown', 9),
  ('OH', 'Lorain', 10),
  ('OK', 'Oklahoma City', 1),
  ('OK', 'Tulsa', 2),
  ('OK', 'Norman', 3),
  ('OK', 'Broken Arrow', 4),
  ('OK', 'Edmond', 5),
  ('OK', 'Lawton', 6),
  ('OK', 'Moore', 7),
  ('OK', 'Midwest City', 8),
  ('OR', 'Portland', 1),
  ('OR', 'Salem', 2),
  ('OR', 'Eugene', 3),
  ('OR', 'Gresham', 4),
  ('OR', 'Hillsboro', 5),
  ('OR', 'Beaverton', 6),
  ('OR', 'Bend', 7),
  ('OR', 'Medford', 8),
  ('OR', 'Springfield', 9),
  ('OR', 'Corvallis', 10),
  ('PA', 'Philadelphia', 1),
  ('PA', 'Pittsburgh', 2),
  ('PA', 'Allentown', 3),
  ('PA', 'Reading', 4),
  ('PA', 'Erie', 5),
  ('PA', 'Scranton', 6),
  ('PA', 'Bethlehem', 7),
  ('PA', 'Lancaster', 8),
  ('PA', 'Harrisburg', 9),
  ('PA', 'York', 10),
  ('RI', 'Providence', 1),
  ('RI', 'Warwick', 2),
  ('RI', 'Cranston', 3),
  ('RI', 'Pawtucket', 4),
  ('RI', 'East Providence', 5),
  ('RI', 'Woonsocket', 6),
  ('RI', 'Newport', 7),
  ('RI', 'Central Falls', 8),
  ('SC', 'Charleston', 1),
  ('SC', 'Columbia', 2),
  ('SC', 'North Charleston', 3),
  ('SC', 'Mount Pleasant', 4),
  ('SC', 'Rock Hill', 5),
  ('SC', 'Greenville', 6),
  ('SC', 'Summerville', 7),
  ('SC', 'Sumter', 8),
  ('SD', 'Sioux Falls', 1),
  ('SD', 'Rapid City', 2),
  ('SD', 'Aberdeen', 3),
  ('SD', 'Brookings', 4),
  ('SD', 'Watertown', 5),
  ('SD', 'Mitchell', 6),
  ('SD', 'Yankton', 7),
  ('SD', 'Pierre', 8),
  ('TN', 'Nashville', 1),
  ('TN', 'Memphis', 2),
  ('TN', 'Knoxville', 3),
  ('TN', 'Chattanooga', 4),
  ('TN', 'Clarksville', 5),
  ('TN', 'Murfreesboro', 6),
  ('TN', 'Franklin', 7),
  ('TN', 'Jackson', 8),
  ('TN', 'Johnson City', 9),
  ('TN', 'Bartlett', 10),
  ('TX', 'Houston', 1),
  ('TX', 'San Antonio', 2),
  ('TX', 'Dallas', 3),
  ('TX', 'Austin', 4),
  ('TX', 'Fort Worth', 5),
  ('TX', 'El Paso', 6),
  ('TX', 'Arlington', 7),
  ('TX', 'Corpus Christi', 8),
  ('TX', 'Plano', 9),
  ('TX', 'Laredo', 10),
  ('TX', 'Lubbock', 11),
  ('TX', 'Garland', 12),
  ('TX', 'Irving', 13),
  ('TX', 'Amarillo', 14),
  ('UT', 'Salt Lake City', 1),
  ('UT', 'West Valley City', 2),
  ('UT', 'Provo', 3),
  ('UT', 'West Jordan', 4),
  ('UT', 'Orem', 5),
  ('UT', 'Sandy', 6),
  ('UT', 'Ogden', 7),
  ('UT', 'St. George', 8),
  ('UT', 'Layton', 9),
  ('UT', 'Taylorsville', 10),
  ('VT', 'Burlington', 1),
  ('VT', 'South Burlington', 2),
  ('VT', 'Rutland', 3),
  ('VT', 'Barre', 4),
  ('VT', 'Montpelier', 5),
  ('VT', 'Winooski', 6),
  ('VT', 'St. Albans', 7),
  ('VT', 'Newport', 8),
  ('VA', 'Virginia Beach', 1),
  ('VA', 'Norfolk', 2),
  ('VA', 'Chesapeake', 3),
  ('VA', 'Richmond', 4),
  ('VA', 'Newport News', 5),
  ('VA', 'Alexandria', 6),
  ('VA', 'Hampton', 7),
  ('VA', 'Roanoke', 8),
  ('VA', 'Portsmouth', 9),
  ('VA', 'Suffolk', 10),
  ('WA', 'Seattle', 1),
  ('WA', 'Spokane', 2),
  ('WA', 'Tacoma', 3),
  ('WA', 'Vancouver', 4),
  ('WA', 'Bellevue', 5),
  ('WA', 'Kent', 6),
  ('WA', 'Everett', 7),
  ('WA', 'Renton', 8),
  ('WA', 'Federal Way', 9),
  ('WA', 'Yakima', 10),
  ('WV', 'Charleston', 1),
  ('WV', 'Huntington', 2),
  ('WV', 'Morgantown', 3),
  ('WV', 'Parkersburg', 4),
  ('WV', 'Wheeling', 5),
  ('WV', 'Weirton', 6),
  ('WV', 'Fairmont', 7),
  ('WV', 'Martinsburg', 8),
  ('WI', 'Milwaukee', 1),
  ('WI', 'Madison', 2),
  ('WI', 'Green Bay', 3),
  ('WI', 'Kenosha', 4),
  ('WI', 'Racine', 5),
  ('WI', 'Appleton', 6),
  ('WI', 'Waukesha', 7),
  ('WI', 'Oshkosh', 8),
  ('WI', 'Eau Claire', 9),
  ('WI', 'Janesville', 10),
  ('WY', 'Cheyenne', 1),
  ('WY', 'Casper', 2),
  ('WY', 'Laramie', 3),
  ('WY', 'Gillette', 4),
  ('WY', 'Rock Springs', 5),
  ('WY', 'Sheridan', 6),
  ('WY', 'Green River', 7),
  ('WY', 'Evanston', 8)
ON CONFLICT (state_code, city_name) DO NOTHING;
