const PRE_HIRE_BASE = "/icons/Hire-icons/pre-hire-icons";
const POST_HIRE_BASE = "/icons/Hire-icons/Post-hire";

/** Maps workflow step ids to Figma hire-library SVG assets. */
export const HIRE_LIBRARY_ICON_PATHS: Record<string, string> = {
  "collect-extra-files": `${PRE_HIRE_BASE}/intake-icons/collect-extra-files.svg`,
  "collect-references": `${PRE_HIRE_BASE}/intake-icons/collect-references.svg`,
  "custom-step": `${PRE_HIRE_BASE}/clipboard-task-list.svg`,
  "resume-basic-profile": `${PRE_HIRE_BASE}/intake-icons/collect-extra-files.svg`,
  "parameterized-job-application": `${PRE_HIRE_BASE}/intake-icons/extra-form.svg`,
  "references-collection": `${PRE_HIRE_BASE}/intake-icons/collect-references.svg`,
  "custom-application-form": `${PRE_HIRE_BASE}/intake-icons/extra-form.svg`,
  "custom-form": `${PRE_HIRE_BASE}/intake-icons/extra-form.svg`,
  "document-upload": `${PRE_HIRE_BASE}/intake-icons/collect-extra-files.svg`,
  "recruiter-screening": `${PRE_HIRE_BASE}/screening-icons/recruiter-screening.svg`,
  "skill-qualification-assessment": `${PRE_HIRE_BASE}/screening-icons/skill-qualification-assessment.svg`,
  "reference-verification": `${PRE_HIRE_BASE}/screening-icons/reference-verification.svg`,
  "interview-qualification": `${PRE_HIRE_BASE}/Interview-icons/interview-qualification.svg`,
  "internal-select": `${PRE_HIRE_BASE}/Interview-icons/internal-select.svg`,
  "client-review": `${PRE_HIRE_BASE}/Interview-icons/interview-qualification.svg`,
  "candidate-selection": `${PRE_HIRE_BASE}/Interview-icons/internal-select.svg`,
  "release-to-client": `${PRE_HIRE_BASE}/submission-icons/sent-to-client-msp.svg`,
  "background-check": `${PRE_HIRE_BASE}/Compliance-icons/background-check.svg`,
  "drug-test-screening": `${PRE_HIRE_BASE}/Compliance-icons/drug-test.svg`,
  "oig-exclusion-check": `${PRE_HIRE_BASE}/Compliance-icons/oig-exclusion.svg`,
  "credential-license-verification": `${PRE_HIRE_BASE}/Compliance-icons/license-check.svg`,
  "ssn-identity-verification": `${PRE_HIRE_BASE}/Compliance-icons/ssn-id.svg`,
  "adverse-action-process": `${PRE_HIRE_BASE}/Compliance-icons/adverse-action.svg`,
  "pay-and-start-date": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/compensation-confirmed.svg`,
  "pay-rate-hire-date": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/start-date-agreed.svg`,
  "offer-accepted": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/offer-letter-sent.svg`,
  "offer-acceptance": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/offer-letter-sent.svg`,
  "agreement-esign": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/agreement-signed.svg`,
  "employee-agreement": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/agreement-signed.svg`,
  "i9-section-1": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/start-date-agreed.svg`,
  "i9-right-to-work-verification": `${PRE_HIRE_BASE}/Offer-and-agreement-icons/start-date-agreed.svg`,
  "i9-section-2": `${POST_HIRE_BASE}/Payroll/i9-everify.svg`,
  "tax-forms": `${POST_HIRE_BASE}/Payroll/w4-state-tax.svg`,
  "manager-facility-approval": `${PRE_HIRE_BASE}/Approval-icons/manager-approval.svg`,
  "hr-final-approval": `${PRE_HIRE_BASE}/Approval-icons/final-approval.svg`,
  "direct-deposit-setup": `${POST_HIRE_BASE}/Payroll/direct-deposit.svg`,
  "benefits-enrollment": `${POST_HIRE_BASE}/Payroll/benefits.svg`,
  "401k-enrollment": `${POST_HIRE_BASE}/Payroll/401k.svg`,
  "payroll-profile-creation": `${POST_HIRE_BASE}/Payroll/create-payroll-profile.svg`,
  "safety-training": `${POST_HIRE_BASE}/training-policy/safety-training.svg`,
  "training-modules-quiz": `${POST_HIRE_BASE}/training-policy/training-modules.svg`,
  "orientation-video": `${POST_HIRE_BASE}/training-policy/orientation-video.svg`,
  "compliance-training": `${POST_HIRE_BASE}/training-policy/compliance-training.svg`,
  "certification-upload": `${POST_HIRE_BASE}/training-policy/cert-upload.svg`,
  "policy-acknowledgment": `${POST_HIRE_BASE}/training-policy/handbook.svg`,
  "welcome-packet-esign": `${POST_HIRE_BASE}/training-policy/welcome-packet.svg`,
  "badge-equipment-issuance": `${POST_HIRE_BASE}/Access-and-system/badge-and-equipment.svg`,
  "schedule-assignment": `${POST_HIRE_BASE}/Access-and-system/first-schedule.svg`,
  "facility-access-setup": `${POST_HIRE_BASE}/Access-and-system/system-door-access.svg`,
  "equipment-badge-acknowledgment": `${POST_HIRE_BASE}/Access-and-system/badge-and-equipment.svg`,
  "welcome-email": `${POST_HIRE_BASE}/Welcome-icons/send-message.svg`,
  "manager-welcome-call": `${POST_HIRE_BASE}/Welcome-icons/manager-welcome-call.svg`,
  "final-onboarding-call": `${POST_HIRE_BASE}/Welcome-icons/final-onboarding-call.svg`,
  "buddy-mentor-assignment": `${POST_HIRE_BASE}/Welcome-icons/buddy-mentor-assignment.svg`,
  "completion-milestone": `${POST_HIRE_BASE}/Welcome-icons/onboarding-complete.svg`,
};

export function resolveHireLibraryIconPath(stepId: string, iconKey?: string): string | null {
  return HIRE_LIBRARY_ICON_PATHS[stepId] ?? (iconKey ? HIRE_LIBRARY_ICON_PATHS[iconKey] ?? null : null);
}
